### ISSUE TITLE
IndexError: The shape of the mask [64, 64] at index 0 does not match the shape of the indexed tensor [3, 4, 85, 64] at index 2

### ISSUE THREAD

**Issue by ShijieGeng** [lsx0101/DiffStyler#2]
IndexError: The shape of the mask [64, 64] at index 0 does not match the shape of the indexed tensor [3, 4, 85, 64] at index 2
execuse me, when i use my mask to run, why happen this.
hope for your review

**Comment by aoyangl2** [comment]
I got the same error, did you solve this?

**Comment by lishaoxu1994** [comment]
I'm sorry I don't have time to fix the code, I may resize the image to a square.
