### ISSUE TITLE
config file question

### ISSUE THREAD

**Issue by soyekwon** [lsx0101/DiffStyler#3]
Thanks for your great job.
I got a question while trying to inference this model
![스크린샷 2024-08-13 오후 3 41 19](https://github.com/user-attachments/assets/2655e048-1ce8-41d6-9e38-848835bf1de8)

What is the role of prompt and prompt_gene in the following files?

Thank you.

**Comment by lishaoxu1994** [comment]
"prompt" is for the original image (you can add descriptions), "prompt_gene" is for the edited image . 
The code is borrowed from Plug-and-Play Diffusion Features for Text-Driven Image-to-Image Translation. (https://github.com/MichalGeyer/pnp-diffusers)

**Comment by soyekwon** [comment]
Thank you.
